############################################################
# Dockerfile to build the development kannji-api server
# Based on Python
############################################################
FROM postgres
LABEL maintainer "Jan-Luca Klees and Johannes Heise"

ADD data/ /var/lib/postgresql/data/