############################################################
# Dockerfile to build the development kannji-api server
# Based on Python
############################################################
FROM postgres:alpine
LABEL maintainer "Jan-Luca Klees and Johannes Heise"

ADD ./data/data/ /var/lib/postgresql/data/